### ISSUE TITLE
[BUG] including a Markdown link under Source metadata breaks rendering

### ISSUE THREAD

**Issue by FekketCantenel** [cooklang/cooklang-ts#10]
This is a cross-post from [a bug in the VS Code Cook Render extension](https://github.com/isaacvando/cookrender/issues/1), which uses this library.

User behavior: The following code at the top of a .cook document.

    >> source: [Small Town Woman](https://www.smalltownwoman.com/easy-matzo-ball-soup/)

Expected result: The following Markdown:

    **source:** [Small Town Woman](https://www.smalltownwoman.com/easy-matzo-ball-soup/)

Actual result:

    ## Small Town Woman
    - (https://www\.smalltownwoman\.com/easy\-matzo\-ball\-soup/)
    - [all remaining metadata are bullet-pointed, and ingredients/steps are not rendered]

According to the extension's dev (see link above), this is because there is no way to specify to the renderer whether this file is a recipe or shopping list. When the renderer sees a `[` (as in a Markdown link), it switches to shopping list mode.

**Comment by ThatTSGuy** [comment]
I don't really know if this should be considered a bug or not, it was never really discussed whether or not .cook files can contain both a recipe and a shopping list or not. I do suppose that the parser should not consider anything in a metadata tag to be a shopping list item. I'll should be able to fix it sometime within the week, or someone can open a pull and I'll accept it.

**Comment by ThatTSGuy** [comment]
Fixed in ba32ab6.
