### ISSUE TITLE
[REQUEST] Expanding AST

### ISSUE THREAD

**Issue by lucharo** [cooklang/cooklang-ts#14]
**Is your feature request related to a problem? Please describe.**
I would like to extend the parsing to include the recipe step for each ingredient, i.e. if aubergine is used in steps 1 and 3, have that information included in the AST, is that possible? I know this is beyond the cooklang spec but I have browsed for cooklang extensions and haven't seen anything. 

**Describe the solution you'd like**
The step number to be included in the AST perhaps through extending the cooklang parser

**Describe alternatives you've considered**
I have browsed for cooklang extensions in different languages (ts, py)

**Comment by ThatTSGuy** [comment]
Can you provide an example of the recipe and it's resulting AST? Just so I can see exactly what your suggesting.

**Comment by lucharo** [comment]
Based on the demo recipe from https://biowaffeln.github.io/cooklang-parser/

Given the recipe:

```cooklang
>> source: https://www.dinneratthezoo.com/wprm_print/6796
>> total time: 6 minutes
>> servings: 2

Place the @apple juice{1,5%cups}, @banana{one sliced}, @frozen mixed berries{1,5%cups} and @vanilla greek yogurt{3/4%cup} in a #blender{}; blend until smooth. If the smoothie seems too thick, add a little more liquid (1/4 cup). 

Taste and add @honey{} if desired. Pour into two glasses and garnish with fresh berries and mint sprigs if desired.
```

I wish for the ingredients section of the AST to include the step index that an ingredient is used in:

```json
{
  "metadata": {
    "source": "https://www.dinneratthezoo.com/wprm_print/6796",
    "total time": "6 minutes",
    "servings": "2"
  },
  "ingredients": [
    {
      "type": "ingredient",
      "name": "apple juice",
      "quantity": "1,5",
      "units": "cups",
      "steps": [1]
    },
    {
      "type": "ingredient",
      "name": "banana",
      "quantity": "one sliced",
      "units": "",
      "steps": [1]
    },
    ...
    {
      "type": "ingredient",
      "name": "honey",
      "quantity": "some",
      "units": "",
      "steps": [2]
    }
  ],
  ...
  }

```

I appreciate the speedy reply

**Comment by ThatTSGuy** [comment]
Done in d459df01. Added new parser option, `includeStepNumber`, see https://cooklang.github.io/cooklang-ts/interfaces/ParserOptions.html.

**Comment by lucharo** [comment]
Super useful! Thanks for the quick turn around!! :)
