### ISSUE TITLE
[REQUEST] Timers as ISO 8601

### ISSUE THREAD

**Issue by MTRNord** [cooklang/cooklang-ts#24]
**Is your feature request related to a problem? Please describe.**

https://www.schema.org/Recipe uses their Duration type for things related to time. That type uses ISO8601. It would be nice to get the values as such to be able to convert to schema.org in renderers.

**Describe the solution you'd like**
A getter for it would be nice

**Describe alternatives you've considered**
Apart from parsing it myself none.

**Additional context**
I guess this may need a spec change to cooklang itself as well.

**Comment by ThatTSGuy** [comment]
I think until the spec changes we will pause this.
