### ISSUE TITLE
[BUG] shoppingList not being generated

### ISSUE THREAD

**Issue by ManeeshChiba** [cooklang/cooklang-ts#26]
It appears that the shopping list is not being generated when invoking `new Parser().parse(source)`. I have attempted to include a `config/aisle.conf` file and still have trouble producing the shopping list.

**To Reproduce**
Here is an example file:
```typescript
// index.ts
import * as Cook from "@cooklang/cooklang-ts";

const source = `
Then add @salt and @ground black pepper{} to taste.
`;

console.log(new Cook.Parser().parse(source).shoppingList);
```
The result is `{}` an empty object.

Alternatively running `cook shopping-list ./FILE_WITH_SAME_CONTENT.cook` produces:
```
$ cook shopping-list ./recipes
INGREDIENTS
    ground black pepper           some
    salt                          some
```

**Expected behavior**
Produce a list of ingredients in the shoppingList field, grouped by the definitions in `config/aisle.conf` should it exist.

**Comment by dubadub** [comment]
Thanks for reporting, I don't think it supports shopping list generation. I think eventually we will migrate it to use WebAssembly version of our rust parser that supports everything, but now we don't have free hands for it.

**Comment by ManeeshChiba** [comment]
Thanks! I appreciate your response.
I'm planning to use the ingredient list for per recipe shopping list for now and will keep an eye out on the wasm build.
