### ISSUE TITLE
Parser greedily gobbles everything between first and last inline comments

### ISSUE THREAD

**Issue by daviesjamie** [cooklang/cooklang-ts#3]
**Describe the bug**
If there's more than one inline comment (using `[- comment -]` syntax) in a recipe file, everything between the opening of the first comment and the closing of the last comment is lost when parsing the recipe file.

This bug is only present in the code on the `main` branch of the repository; it has not yet been released to npm.

**To Reproduce**
An example that reproduces the issue:

```ts
import { Parser } from "@cooklang/cooklang-ts";

const source = "Add some [- comment -] @salt and [- another comment -] @pepper";
const recipe = new Parser().parse(source);

console.log(recipe.steps);
```

When running this against the code in the npm release:

```sh
$ npm install @cooklang/cooklang-ts
```

This outputs:

```ts
[
  [
    { type: 'text', value: 'Add some ' },
    { type: 'ingredient', name: 'salt', quantity: 'some' },
    { type: 'text', value: ' and ' },
    { type: 'ingredient', name: 'pepper', quantity: 'some' }
  ]
]
```

However, when running against the code in the `main` branch:

```sh
$ npm uninstall @cooklang/cooklang-ts
$ npm install https://github.com/cooklang/cooklang-ts
```

This outputs:

```ts
[
  [
    { type: 'text', value: 'Add some ' },
    { type: 'ingredient', name: 'pepper' }
  ]
]
```

**Expected behavior**
I expected the salt in the recipe to not be ignored!

**Additional context**
I think this is almost certainly because the regex matching that strips out comments at the start of parsing is being too greedy, and is matching everything between the first comment opening character and last comment closing character.

In the short term this can probably be fixed by adjusting the regex, but I think in the long-term a more robust token-based lexer/parser algorithm could be considered (similar to what is already done in [cooklang-swift](https://github.com/cooklang/cooklang-swift/blob/main/Sources/CookInSwift/Parser/Parser.swift)) to avoid the inherent fragility of regex matching.

**Comment by ThatTSGuy** [comment]
Fixed in 10e3e02.
