### ISSUE TITLE
Parser incorrectly detecting end of timer units

### ISSUE THREAD

**Issue by daviesjamie** [cooklang/cooklang-ts#6]
**Describe the bug**
Sometimes the parser fails to detect the closing `}` after a timer declaration, and instead parses all of the following text as a unit for that timer.

**To Reproduce**
This is a simple script that reproduces the behaviour:

```ts
import { Parser } from "@cooklang/cooklang-ts";

const source = `Continue frying for ~{1%minute}. Add the @garlic{1%clove}.`;
const recipe = new Parser().parse(source);
console.log(JSON.stringify(recipe, null, 2));
```

This outputs:

```
{
  "metadata": {},
  "steps": [
    [
      {
        "type": "text",
        "value": "Continue frying for "
      },
      {
        "type": "timer",
        "name": "",
        "quantity": 1,
        "units": "minute}. Add the @garlic{1%clove"
      },
      {
        "type": "text",
        "value": "."
      }
    ]
  ],
  "shoppingList": {}
}
```

I've tested against the published npm version (`1.0.0`) and the latest code on `main`.

**Expected behavior**
In the above example, I expected the timer to have a unit of `minute` (or `minutes`), and for the following text and ingredient to be parsed correctly.

**Comment by ThatTSGuy** [comment]
Thanks! Fixed in 9ca8794.
